{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Validation error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ml_validation_errors_total[5m]) / (rate(ml_predictions_total[5m]) + rate(ml_validation_errors_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(ml_predictions_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(ml_inference_latency_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bar chart (ou Pie)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (model) (ml_predictions_by_model_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}